# Generated by Django 3.1.4 on 2020-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentadeahorro',
            fields=[
                ('codigocuenta', models.BigIntegerField(db_column='codigoCuenta', primary_key=True, serialize=False)),
                ('tasainteres', models.IntegerField(db_column='tasaInteres')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'cuentadeahorro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentamonetaria',
            fields=[
                ('codigocuenta', models.BigIntegerField(db_column='codigoCuenta', primary_key=True, serialize=False)),
                ('montopormanejo', models.DecimalField(blank=True, db_column='montoPorManejo', decimal_places=2, max_digits=5, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'cuentamonetaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentaplazofijo',
            fields=[
                ('codigocuenta', models.BigIntegerField(db_column='codigoCuenta', primary_key=True, serialize=False)),
                ('tasainteres', models.IntegerField(db_column='tasaInteres')),
                ('periododetiempo', models.IntegerField(db_column='periodoDeTiempo')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'cuentaplazofijo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleclientecuenta',
            fields=[
                ('codigodetalle', models.AutoField(db_column='codigoDetalle', primary_key=True, serialize=False)),
                ('estaactiva', models.IntegerField(db_column='estaActiva')),
            ],
            options={
                'db_table': 'detalleclientecuenta',
                'managed': False,
            },
        ),
    ]
